const os = require('node:os');
console.log(os.freemem());
console.log(os.arch());
console.log(os.platform());
console.log(os.type());
console.log(os.hostname());
console.log(os.totalmem());
console.log(os.cpus());
console.log(os.networkInterfaces());
console.log(os.homedir());
